pages_build_output_dir = "public"
name = "epir-landing"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LANDING_CONFIG"
id = "08f16276a9b14ca7b3c00404e8e8d0d9"
preview_id = "08f16276a9b14ca7b3c00404e8e8d0d9"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "autorag-epir-website-rag-0b92dc"